# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(320, 40, 191, 81))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 130, 261, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_FIO = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_FIO.setInputMask("")
        self.lineEdit_FIO.setText("")
        self.lineEdit_FIO.setMaxLength(32767)
        self.lineEdit_FIO.setObjectName("lineEdit_FIO")
        self.verticalLayout.addWidget(self.lineEdit_FIO)
        self.lineEdit_num = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_num.setInputMask("")
        self.lineEdit_num.setText("")
        self.lineEdit_num.setMaxLength(32767)
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.verticalLayout.addWidget(self.lineEdit_num)
        self.lineEdit_email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_email.setInputMask("")
        self.lineEdit_email.setText("")
        self.lineEdit_email.setMaxLength(32767)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout.addWidget(self.lineEdit_email)
        self.lineEdit_date = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_date.setInputMask("")
        self.lineEdit_date.setText("")
        self.lineEdit_date.setMaxLength(32767)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.verticalLayout.addWidget(self.lineEdit_date)
        self.pushButton_reg = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_reg.setGeometry(QtCore.QRect(250, 440, 259, 23))
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Регистрация клиента"))
        self.lineEdit_FIO.setPlaceholderText(_translate("MainWindow", "ФИО"))
        self.lineEdit_num.setPlaceholderText(_translate("MainWindow", "Телефон"))
        self.lineEdit_email.setPlaceholderText(_translate("MainWindow", "Почта"))
        self.lineEdit_date.setPlaceholderText(_translate("MainWindow", "Дата рождения"))
        self.pushButton_reg.setText(_translate("MainWindow", "Внести"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Регистрация"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Заказы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Пользователи"))
