# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\rabota\interface\Clients.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientDialog(object):
    def setupUi(self, ClientDialog):
        ClientDialog.setObjectName("ClientDialog")
        ClientDialog.resize(800, 567)
        ClientDialog.setMinimumSize(QtCore.QSize(800, 567))
        ClientDialog.setMaximumSize(QtCore.QSize(800, 567))
        ClientDialog.setStyleSheet("background-color: rgb(98, 98, 98);")
        self.centralwidget = QtWidgets.QWidget(ClientDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -1, 801, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TextClient_FIO = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.TextClient_FIO.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"\n"
"")
        self.TextClient_FIO.setObjectName("TextClient_FIO")
        self.verticalLayout.addWidget(self.TextClient_FIO)
        self.TextClient_num = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.TextClient_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"\n"
"")
        self.TextClient_num.setObjectName("TextClient_num")
        self.verticalLayout.addWidget(self.TextClient_num)
        self.TextClient_email = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.TextClient_email.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"\n"
"")
        self.TextClient_email.setObjectName("TextClient_email")
        self.verticalLayout.addWidget(self.TextClient_email)
        self.TextClient_date = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.TextClient_date.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"\n"
"")
        self.TextClient_date.setObjectName("TextClient_date")
        self.verticalLayout.addWidget(self.TextClient_date)
        self.pushButton_changeClient = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_changeClient.setGeometry(QtCore.QRect(620, 500, 171, 31))
        self.pushButton_changeClient.setStyleSheet("border-radius: 10%;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_changeClient.setObjectName("pushButton_changeClient")
        self.pushButton_deleteClient = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteClient.setGeometry(QtCore.QRect(10, 500, 171, 31))
        self.pushButton_deleteClient.setStyleSheet("border-radius: 10%;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 106, 108);")
        self.pushButton_deleteClient.setObjectName("pushButton_deleteClient")
        self.pushButton_blackList = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_blackList.setGeometry(QtCore.QRect(320, 500, 171, 31))
        self.pushButton_blackList.setStyleSheet("border-radius: 10%;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_blackList.setObjectName("pushButton_blackList")
        self.groupBox_change = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_change.setGeometry(QtCore.QRect(0, 390, 801, 181))
        self.groupBox_change.setStyleSheet("background-color: rgb(98, 98, 98);\n"
"border-radius: 1px;\n"
"")
        self.groupBox_change.setTitle("")
        self.groupBox_change.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_change.setFlat(True)
        self.groupBox_change.setCheckable(False)
        self.groupBox_change.setObjectName("groupBox_change")
        self.textBrowser_errCheckClients_2 = QtWidgets.QTextBrowser(self.groupBox_change)
        self.textBrowser_errCheckClients_2.setGeometry(QtCore.QRect(320, 18, 441, 31))
        self.textBrowser_errCheckClients_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser_errCheckClients_2.setObjectName("textBrowser_errCheckClients_2")
        self.lineEdit_changeFIOClient = QtWidgets.QLineEdit(self.groupBox_change)
        self.lineEdit_changeFIOClient.setGeometry(QtCore.QRect(10, 30, 251, 31))
        self.lineEdit_changeFIOClient.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"border-bottom: 1px solid white;\n"
"border-top: none; \n"
"border-left: none; \n"
"border-right: none;\n"
"\n"
"\n"
"")
        self.lineEdit_changeFIOClient.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_changeFIOClient.setObjectName("lineEdit_changeFIOClient")
        self.lineEdit_changeNumClient = QtWidgets.QLineEdit(self.groupBox_change)
        self.lineEdit_changeNumClient.setGeometry(QtCore.QRect(280, 30, 251, 31))
        self.lineEdit_changeNumClient.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"border-bottom: 1px solid white;\n"
"border-top: none; \n"
"border-left: none; \n"
"border-right: none;\n"
"\n"
"\n"
"\n"
"")
        self.lineEdit_changeNumClient.setText("")
        self.lineEdit_changeNumClient.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_changeNumClient.setObjectName("lineEdit_changeNumClient")
        self.lineEdit_changeEmailClient = QtWidgets.QLineEdit(self.groupBox_change)
        self.lineEdit_changeEmailClient.setGeometry(QtCore.QRect(550, 30, 241, 31))
        self.lineEdit_changeEmailClient.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"border-bottom: 1px solid white;\n"
"border-top: none; \n"
"border-left: none; \n"
"border-right: none;\n"
"\n"
"")
        self.lineEdit_changeEmailClient.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_changeEmailClient.setObjectName("lineEdit_changeEmailClient")
        self.lineEdit_changeDateClient = QtWidgets.QLineEdit(self.groupBox_change)
        self.lineEdit_changeDateClient.setGeometry(QtCore.QRect(280, 80, 251, 31))
        self.lineEdit_changeDateClient.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"border-bottom: 1px solid white;\n"
"border-top: none; \n"
"border-left: none; \n"
"border-right: none;\n"
"\n"
"")
        self.lineEdit_changeDateClient.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_changeDateClient.setObjectName("lineEdit_changeDateClient")
        self.pushButton_changeCancel = QtWidgets.QPushButton(self.groupBox_change)
        self.pushButton_changeCancel.setGeometry(QtCore.QRect(590, 120, 171, 31))
        self.pushButton_changeCancel.setStyleSheet("border-radius: 10%;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_changeCancel.setObjectName("pushButton_changeCancel")
        self.pushButton_Accept = QtWidgets.QPushButton(self.groupBox_change)
        self.pushButton_Accept.setGeometry(QtCore.QRect(50, 120, 171, 31))
        self.pushButton_Accept.setStyleSheet("border-radius: 10%;\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_Accept.setObjectName("pushButton_Accept")
        ClientDialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ClientDialog)
        self.statusbar.setObjectName("statusbar")
        ClientDialog.setStatusBar(self.statusbar)

        self.retranslateUi(ClientDialog)
        QtCore.QMetaObject.connectSlotsByName(ClientDialog)

    def retranslateUi(self, ClientDialog):
        _translate = QtCore.QCoreApplication.translate
        ClientDialog.setWindowTitle(_translate("ClientDialog", "Клиент"))
        self.TextClient_FIO.setHtml(_translate("ClientDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TextClient_num.setHtml(_translate("ClientDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TextClient_email.setHtml(_translate("ClientDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TextClient_date.setHtml(_translate("ClientDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_changeClient.setText(_translate("ClientDialog", "Изменить"))
        self.pushButton_deleteClient.setText(_translate("ClientDialog", "Удалить Клиента"))
        self.pushButton_blackList.setText(_translate("ClientDialog", "Добавить в ЧС"))
        self.textBrowser_errCheckClients_2.setHtml(_translate("ClientDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lineEdit_changeFIOClient.setPlaceholderText(_translate("ClientDialog", "ФИО клиента"))
        self.lineEdit_changeNumClient.setPlaceholderText(_translate("ClientDialog", "Телефон"))
        self.lineEdit_changeEmailClient.setPlaceholderText(_translate("ClientDialog", "Почта"))
        self.lineEdit_changeDateClient.setPlaceholderText(_translate("ClientDialog", "Дата рождения"))
        self.pushButton_changeCancel.setText(_translate("ClientDialog", "Отмена"))
        self.pushButton_Accept.setText(_translate("ClientDialog", "Принять"))
