# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\rabota\interface\Warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 110)
        Dialog.setMaximumSize(QtCore.QSize(321, 110))
        Dialog.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 331, 71))
        self.textBrowser.setStyleSheet("border: 0px;")
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_OK = QtWidgets.QPushButton(Dialog)
        self.pushButton_OK.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.pushButton_OK.setStyleSheet("background-color: rgb(158, 158, 158);\n"
"border: 0px;\n"
"border-radius: 10%;\n"
"font: 87 8pt \"Segoe UI Black\";")
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(240, 80, 75, 23))
        self.pushButton_cancel.setStyleSheet("background-color: rgb(158, 158, 158);\n"
"border: 0px;\n"
"border-radius: 10%;\n"
"font: 87 8pt \"Segoe UI Black\";")
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Предупреждение"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Black\'; font-size:12pt; color:#ffffff;\">Внимание: при удалении клиента, удаляются все заказы,<br /> связанные с клиентом!</span></p></body></html>"))
        self.pushButton_OK.setText(_translate("Dialog", "Ок"))
        self.pushButton_cancel.setText(_translate("Dialog", "Отмена"))
